### ISSUE TITLE
Add `arrays` as an alias for the `recurse_over_arrays` constructor option

### ISSUE THREAD

**Issue by Nowaker** [aetherknight/recursive-open-struct#15]
```
RecursiveOpenStruct.new object, recurse_over_arrays: true
```
This code resembles me Java. Let's change it to `RecursiveOpenStruct.new object, arrays: true`. It's obvious that "arrays" stands for resursing over them.

**Comment by aetherknight** [comment]
Closing this out because no PR was submitted and it has been over a year.
