### ISSUE TITLE
is there support to create ROS in an object oriented way?

### ISSUE THREAD

**Issue by abonas** [aetherknight/recursive-open-struct#20]
All the examples I saw are creating ROS by "feeding" it a hash (with nested hashes)
Does it support creating ROS by setting its attributes one by one, specifically with nested attributes too?

Example:
service1 = RecursiveOpenStruct.new
service1.id = 12345
service.name ="redis"
service1.resources.memory="xyz"
service1.resources.cpu ="abc"

the above example fails on the part where there's a nested level (resources.memory and resources.cpu) with "undefined method `memory=' for nil:NilClass (NoMethodError)"

**Comment by u2** [comment]
You can write like below.
```
service1 = RecursiveOpenStruct.new
service1.id = 12345
service1.name ="redis"
service1.resources = {}
service1.resources.memory="xyz"
service1.resources.cpu ="abc"
```
