### ISSUE TITLE
on ruby 2.3.1 recurse_over_arrays doesnt work

### ISSUE THREAD

**Issue by kubenstein** [aetherknight/recursive-open-struct#48]
hi,
recently i switched to newer ruby in one of my project and noticed `recurse_over_arrays` option doesnt work any longer. Looks like it still is just a hash.
Im not sure how it is on other ruby versions.

Thank you

```
2.3.1 :001 > require 'recursive-open-struct'
 => true 
2.3.1 :002 > ros = RecursiveOpenStruct.new({array: [{field: 'value'}]}, recurse_over_arrays: true)
 => #<RecursiveOpenStruct array=[{:field=>"value"}]> 
2.3.1 :003 > ros.array[0].field
NoMethodError: undefined method `field' for {:field=>"value"}:Hash
    from (irb):3
    from /Users/kuba/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by 31piy** [comment]
@kubenstein Which revision are you using? I used `ruby 2.3.1p112` and run the same code. Found that it is working.

**Comment by kubenstein** [comment]
hey hey i reinstalled everything, not sure what version of the gem I was using, should have included this in the pr, BUT with `recursive-open-struct-1.0.1` and on ruby `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]` all is working again. thank you and sorry for false alert.
