### ISSUE TITLE
Do you follow SemVer? If yes, can you mention it in README/Changelog?

### ISSUE THREAD

**Issue by pravi** [aetherknight/recursive-open-struct#57]
Most projects assume there is no SemVer when there is no explicit declaration. So kubeclient has ~> 1.0.4 as requirement for recursive-open-struct. This means I have to maintain a patch in debian to be able to install 1.1.0 version. If you state your semver compliance, I can ask kubeclient maintainer to relax the dependency to ~> 1.0.

**Comment by aetherknight** [comment]
Hey @pravi recursive-open-struct does follow semver. I will add a statement about it to the readme.
