### ISSUE TITLE
Failures using marshal_dump with v1.3.0

### ISSUE THREAD

**Issue by agrare** [aetherknight/recursive-open-struct#79]
We started hitting failures related to `RecursiveOpenStruct#marshal_dump` that appear to be introduced by #72 
The return value is different causing callers that assume the same API contract, specifically something like `ros.marshal_dump.each { |key, val| ... }` now fails because it is iterating over an array of the ostruct and the options.

Example code that fails: https://github.com/fog/fog-kubevirt/blob/master/lib/fog/kubevirt/compute/compute.rb#L94-L97
Related Issue: https://github.com/fog/fog-kubevirt/issues/161

Since this changes the return format IMO this was a breaking change and should have been a major version release.

**Comment by Fryguy** [comment]
Note that marshal_dump and marshal_load were inherited from ostruct with this implementation: https://github.com/ruby/ostruct/blob/master/lib/ostruct.rb#L217-L227, and the new interface in #72  changes that contract.

**Comment by aetherknight** [comment]
Apologies, I didn’t consider how this might’ve been a breaking change when I merged #72 .

I’ll push a patch release later today to revert the marshal_dump change, and will move the marshal_dump change to a new major release.

**Comment by aetherknight** [comment]
I pushed 1.3.1, which reverts the marshalling changes

**Comment by aetherknight** [comment]
And restored #72 and released as major version 2.0.0

**Comment by agrare** [comment]
:bow: thanks for the quick fix @aetherknight !
